#!/usr/bin/env python3
"""
Verify MF4 file generated by mf4_parse using asammdf library.
Compares the written data against the expected values.
"""

import numpy as np
from asammdf import MDF

# Expected data generation parameters (must match main.rs)
DURATION_SEC = 10.0

# Fast sampling: 10ms period = 100 samples/sec
PERIOD_FAST = 0.01
N_FAST = int(DURATION_SEC / PERIOD_FAST)

# Medium sampling: 50ms period = 20 samples/sec
PERIOD_MEDIUM = 0.05
N_MEDIUM = int(DURATION_SEC / PERIOD_MEDIUM)

# Slow sampling: 100ms period = 10 samples/sec
PERIOD_SLOW = 0.1
N_SLOW = int(DURATION_SEC / PERIOD_SLOW)


def generate_expected_data():
    """Generate expected data matching main.rs logic."""

    # Fast sampling data
    time_fast_data = np.array([i * PERIOD_FAST for i in range(N_FAST)])
    sine_data = np.sin(2.0 * np.pi * time_fast_data)
    cosine_data = np.cos(2.0 * np.pi * time_fast_data)

    # Medium sampling data
    time_medium_data = np.array([i * PERIOD_MEDIUM for i in range(N_MEDIUM)])
    # Square wave: 0.5Hz, toggles every 1 second
    square_data = np.array([1.0 if (int(t * 0.5) % 2 == 0) else 0.0 for t in time_medium_data])
    # Counter: 0-255, wrapping
    counter_data = np.array([i % 256 for i in range(N_MEDIUM)], dtype=np.uint8)

    # Slow sampling data
    time_slow_data = np.array([i * PERIOD_SLOW for i in range(N_SLOW)])
    # Random noise: pseudo-random using linear congruential generator (match Rust logic)
    state = 12345
    random_data = []
    for _ in range(N_SLOW):
        state = (state * 1103515245 + 12345) % (2**64)
        value = (state % 1000) / 100.0 - 5.0  # Range: -5.0 to 5.0
        random_data.append(value)
    random_data = np.array(random_data)
    # Status: cycle through 0,1,2,3 every 2 seconds
    status_data = np.array([int(t / 2.0) % 4 for t in time_slow_data], dtype=np.uint8)

    return {
        'fast': {
            'time_fast': time_fast_data,
            'SineWave': sine_data,
            'CosineWave': cosine_data,
        },
        'medium': {
            'time_medium': time_medium_data,
            'SquareWave': square_data,
            'Counter': counter_data,
        },
        'slow': {
            'time_slow': time_slow_data,
            'RandomNoise': random_data,
            'Status': status_data,
        }
    }


def verify_channel_data(mdf, channel_name, expected_data, tolerance=1e-10):
    """Verify a single channel's data against expected values."""
    print(f"\n  Verifying channel: {channel_name}")

    # Get channel data from MDF
    try:
        signal = mdf.get(channel_name)
        actual_data = signal.samples
        actual_timestamps = signal.timestamps
    except Exception as e:
        print(f"    ERROR: Failed to get channel data: {e}")
        return False

    # Check sample count
    if len(actual_data) != len(expected_data):
        print(f"    ERROR: Sample count mismatch: expected {len(expected_data)}, got {len(actual_data)}")
        return False

    print(f"    Sample count: {len(actual_data)}")

    # Convert to native byte order for proper comparison
    if actual_data.dtype.byteorder == '>':
        actual_data = actual_data.astype(actual_data.dtype.newbyteorder('='))

    # Check data type
    print(f"    Expected dtype: {expected_data.dtype}, Actual dtype: {actual_data.dtype}")

    # Compare values
    if np.issubdtype(expected_data.dtype, np.floating):
        # Floating point comparison with tolerance
        max_diff = np.max(np.abs(actual_data - expected_data))
        if max_diff > tolerance:
            print(f"    ERROR: Max difference {max_diff} exceeds tolerance {tolerance}")
            # Show some samples for debugging
            for i in range(min(5, len(actual_data))):
                print(f"      [{i}] expected: {expected_data[i]:.10f}, actual: {actual_data[i]:.10f}, diff: {abs(expected_data[i] - actual_data[i]):.10e}")
            return False
        print(f"    Max difference: {max_diff:.10e} (within tolerance {tolerance})")
    else:
        # Integer comparison - exact match
        if not np.array_equal(actual_data, expected_data):
            diff_indices = np.where(actual_data != expected_data)[0]
            print(f"    ERROR: {len(diff_indices)} samples don't match")
            for i in diff_indices[:5]:
                print(f"      [{i}] expected: {expected_data[i]}, actual: {actual_data[i]}")
            return False
        print(f"    All samples match exactly")

    # Check first and last few samples
    print(f"    First 5 samples: {actual_data[:5]}")
    print(f"    Last 5 samples: {actual_data[-5:]}")

    return True


def verify_conversion(mdf, channel_name, expected_texts):
    """Verify Value2Text conversion is applied correctly."""
    print(f"\n  Checking conversion for: {channel_name}")

    try:
        signal = mdf.get(channel_name)
        # Check if conversion exists
        if hasattr(signal, 'conversion') and signal.conversion:
            print(f"    Conversion found: {signal.conversion}")

        # Get raw values and check they map correctly
        raw_values = signal.samples
        print(f"    Raw values unique: {np.unique(raw_values)}")
        print(f"    Raw values first 10: {raw_values[:10]}")

        # Try to get raw numeric data
        raw_signal = mdf.get(channel_name, raw=True)
        print(f"    Raw signal samples: {raw_signal.samples[:10]}")
        print(f"    Raw signal dtype: {raw_signal.samples.dtype}")

    except Exception as e:
        print(f"    Note: Could not verify conversion: {e}")


def main():
    import sys
    mf4_path = sys.argv[1] if len(sys.argv) > 1 else "test/time_series_demo.mf4"

    print("=" * 60)
    print("MF4 File Verification using asammdf")
    print("=" * 60)
    print(f"\nLoading MF4 file: {mf4_path}")

    try:
        mdf = MDF(mf4_path)
    except Exception as e:
        print(f"ERROR: Failed to load MF4 file: {e}")
        return False

    # Print file info
    print(f"\nFile version: {mdf.version}")

    # List all channels
    channels = mdf.channels_db.keys()
    print(f"\nChannels found ({len(channels)}):")
    for ch in sorted(channels):
        print(f"  - {ch}")

    # Generate expected data
    print("\nGenerating expected data...")
    expected = generate_expected_data()

    # Verify each channel group
    all_passed = True

    print("\n" + "=" * 60)
    print("Channel Group 1: Fast Sampling (100Hz)")
    print("=" * 60)
    for ch_name, ch_data in expected['fast'].items():
        if not verify_channel_data(mdf, ch_name, ch_data):
            all_passed = False

    print("\n" + "=" * 60)
    print("Channel Group 2: Medium Sampling (20Hz)")
    print("=" * 60)
    for ch_name, ch_data in expected['medium'].items():
        if not verify_channel_data(mdf, ch_name, ch_data):
            all_passed = False

    print("\n" + "=" * 60)
    print("Channel Group 3: Slow Sampling (10Hz)")
    print("=" * 60)
    for ch_name, ch_data in expected['slow'].items():
        # Skip Status channel for normal verification - it has conversion
        if ch_name == "Status":
            continue
        if not verify_channel_data(mdf, ch_name, ch_data):
            all_passed = False

    # Special verification for Status channel with Value2Text conversion
    print("\n  Verifying channel: Status (with Value2Text conversion)")
    raw_status = mdf.get("Status", raw=True)
    expected_status = expected['slow']['Status']
    if np.array_equal(raw_status.samples, expected_status):
        print("    Raw Status data MATCHES expected values!")
        print(f"    Raw values: {raw_status.samples[:10]}...")
    else:
        print("    ERROR: Raw Status data does not match!")
        print(f"    Expected: {expected_status[:10]}")
        print(f"    Actual: {raw_status.samples[:10]}")
        all_passed = False

    # Verify conversion is applied correctly
    converted_status = mdf.get("Status")
    print(f"    Converted values (first 10): {converted_status.samples[:10]}")
    expected_texts = ["Normal", "Not Good", "Error", "Emergency"]
    # Check that conversion maps correctly: 0->Normal, 1->Not Good, 2->Error, 3->Emergency
    for i, expected_text in enumerate(expected_texts):
        if expected_text.encode() in converted_status.samples:
            print(f"    Conversion {i} -> '{expected_text}' verified")
        else:
            print(f"    WARNING: '{expected_text}' not found in converted samples")

    # Summary
    print("\n" + "=" * 60)
    if all_passed:
        print("VERIFICATION PASSED: All channels match expected data!")
    else:
        print("VERIFICATION FAILED: Some channels have mismatched data!")
    print("=" * 60)

    mdf.close()
    return all_passed


if __name__ == "__main__":
    success = main()
    sys.exit(0 if success else 1)
